name: microbiome_classif
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - xgboost=3.1.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - umap-learn=0.5.3
  - tqdm=4.65.0
  - jupyterlab=3.6.3
  - ipywidgets=8.0.6
  - jupyter_contrib_nbextensions=0.7.0
  - notebook=6.5.4
  - ipykernel=6.22.0
